name: OWASP dependency check

on:
  workflow_call:
jobs:
    depchecktest:
        runs-on: ubuntu-latest
        name: depecheck_test
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Cache Dependency-Check data
          uses: actions/cache@v2
          with:
            path: |
                ~/.m2/repository
                ~/dependency-check-data
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                ${{ runner.os }}-maven-
        - name: Build project with Maven
          run: mvn clean install
        - name: Depcheck
          uses: dependency-check/Dependency-Check_Action@main
          id: Depcheck
          with:
            project: 'test'
            path: '.'
            format: 'HTML'
            out: 'reports' # this is the default, no need to specify unless you wish to override it
            args: >
                --failOnCVSS 7
                --enableRetired
                --enableExperimental
        - name: Upload Test results
          uses: actions/upload-artifact@master
          with:
              name: Depcheck report
              path: ${{github.workspace}}/reports